// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Models;

namespace api.Migrations
{
    [DbContext(typeof(CoffeeContext))]
    [Migration("20191015223729_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("api.Models.DiscountCodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("percentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiscountCodes");
                });

            modelBuilder.Entity("api.Models.InvoiceItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<int>("ProductOptionID")
                        .HasColumnType("int");

                    b.Property<int>("opt_price")
                        .HasColumnType("int");

                    b.Property<int>("opt_weight")
                        .HasColumnType("int");

                    b.Property<int>("prod_altitude_max")
                        .HasColumnType("int");

                    b.Property<int>("prod_altitude_min")
                        .HasColumnType("int");

                    b.Property<string>("prod_bean_type")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("prod_desc")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("prod_image_url")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("prod_name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("prod_region")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("prod_roast")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceID");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("api.Models.Invoices", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("discount_code")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("discount_percentage")
                        .HasColumnType("int");

                    b.Property<byte>("isFreeShipping")
                        .HasColumnType("tinyint");

                    b.Property<int>("tax")
                        .HasColumnType("int");

                    b.Property<int>("total")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("api.Models.ProductOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<byte>("isAvailable")
                        .HasColumnType("tinyint");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<int>("weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductID = 1,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(6568),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 8000,
                            quantity = 15,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(7096),
                            weight = 250
                        },
                        new
                        {
                            Id = 2,
                            ProductID = 1,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8690),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 15000,
                            quantity = 15,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8694),
                            weight = 500
                        },
                        new
                        {
                            Id = 3,
                            ProductID = 1,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8707),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 28000,
                            quantity = 15,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8708),
                            weight = 1000
                        },
                        new
                        {
                            Id = 4,
                            ProductID = 2,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8710),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 9000,
                            quantity = 10,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8710),
                            weight = 250
                        },
                        new
                        {
                            Id = 5,
                            ProductID = 2,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8711),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 15000,
                            quantity = 11,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8712),
                            weight = 500
                        },
                        new
                        {
                            Id = 6,
                            ProductID = 2,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8713),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 31000,
                            quantity = 12,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8714),
                            weight = 1000
                        },
                        new
                        {
                            Id = 7,
                            ProductID = 3,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8715),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 10000,
                            quantity = 13,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8715),
                            weight = 250
                        },
                        new
                        {
                            Id = 8,
                            ProductID = 3,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8716),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 22000,
                            quantity = 25,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8717),
                            weight = 500
                        },
                        new
                        {
                            Id = 9,
                            ProductID = 3,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8718),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 32000,
                            quantity = 5,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8719),
                            weight = 1000
                        },
                        new
                        {
                            Id = 10,
                            ProductID = 4,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8720),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 6000,
                            quantity = 13,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8721),
                            weight = 250
                        },
                        new
                        {
                            Id = 11,
                            ProductID = 4,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8722),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 14000,
                            quantity = 35,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8722),
                            weight = 500
                        },
                        new
                        {
                            Id = 12,
                            ProductID = 4,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8723),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 25000,
                            quantity = 19,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8724),
                            weight = 1000
                        },
                        new
                        {
                            Id = 13,
                            ProductID = 5,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8725),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 8000,
                            quantity = 16,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8726),
                            weight = 250
                        },
                        new
                        {
                            Id = 14,
                            ProductID = 5,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8727),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 12000,
                            quantity = 17,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8727),
                            weight = 500
                        },
                        new
                        {
                            Id = 15,
                            ProductID = 5,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8728),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 16000,
                            quantity = 11,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8729),
                            weight = 1000
                        },
                        new
                        {
                            Id = 16,
                            ProductID = 6,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8730),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 15000,
                            quantity = 33,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8730),
                            weight = 250
                        },
                        new
                        {
                            Id = 17,
                            ProductID = 6,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8732),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 20000,
                            quantity = 25,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8732),
                            weight = 500
                        },
                        new
                        {
                            Id = 18,
                            ProductID = 6,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8733),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 35000,
                            quantity = 19,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8734),
                            weight = 1000
                        },
                        new
                        {
                            Id = 19,
                            ProductID = 7,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8735),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 10000,
                            quantity = 16,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8736),
                            weight = 250
                        },
                        new
                        {
                            Id = 20,
                            ProductID = 7,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8737),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 19000,
                            quantity = 15,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8739),
                            weight = 500
                        },
                        new
                        {
                            Id = 21,
                            ProductID = 7,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8740),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 29000,
                            quantity = 17,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8740),
                            weight = 1000
                        },
                        new
                        {
                            Id = 22,
                            ProductID = 8,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8742),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 10000,
                            quantity = 17,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8742),
                            weight = 250
                        },
                        new
                        {
                            Id = 23,
                            ProductID = 8,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8743),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 13500,
                            quantity = 13,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8744),
                            weight = 500
                        },
                        new
                        {
                            Id = 24,
                            ProductID = 8,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8745),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 17000,
                            quantity = 25,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8745),
                            weight = 1000
                        },
                        new
                        {
                            Id = 25,
                            ProductID = 9,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8746),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 18000,
                            quantity = 35,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8747),
                            weight = 250
                        },
                        new
                        {
                            Id = 26,
                            ProductID = 9,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8748),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 26000,
                            quantity = 11,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8749),
                            weight = 500
                        },
                        new
                        {
                            Id = 27,
                            ProductID = 9,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8750),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 32000,
                            quantity = 9,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8750),
                            weight = 1000
                        },
                        new
                        {
                            Id = 28,
                            ProductID = 10,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8751),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 10000,
                            quantity = 15,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8752),
                            weight = 250
                        },
                        new
                        {
                            Id = 29,
                            ProductID = 10,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8753),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 19000,
                            quantity = 21,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8754),
                            weight = 500
                        },
                        new
                        {
                            Id = 30,
                            ProductID = 10,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8755),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 36000,
                            quantity = 11,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8755),
                            weight = 1000
                        },
                        new
                        {
                            Id = 31,
                            ProductID = 11,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8756),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 8000,
                            quantity = 7,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8757),
                            weight = 250
                        },
                        new
                        {
                            Id = 32,
                            ProductID = 11,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8758),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 15000,
                            quantity = 13,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8759),
                            weight = 500
                        },
                        new
                        {
                            Id = 33,
                            ProductID = 11,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8760),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 28000,
                            quantity = 33,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8761),
                            weight = 1000
                        },
                        new
                        {
                            Id = 34,
                            ProductID = 12,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8762),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 8000,
                            quantity = 6,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8763),
                            weight = 250
                        },
                        new
                        {
                            Id = 35,
                            ProductID = 12,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8764),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 15000,
                            quantity = 7,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8765),
                            weight = 500
                        },
                        new
                        {
                            Id = 36,
                            ProductID = 12,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8766),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 28000,
                            quantity = 8,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8767),
                            weight = 1000
                        },
                        new
                        {
                            Id = 37,
                            ProductID = 13,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8768),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 8000,
                            quantity = 22,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8769),
                            weight = 250
                        },
                        new
                        {
                            Id = 38,
                            ProductID = 13,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8770),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 15000,
                            quantity = 11,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8771),
                            weight = 500
                        },
                        new
                        {
                            Id = 39,
                            ProductID = 13,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8772),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 28000,
                            quantity = 44,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8772),
                            weight = 1000
                        },
                        new
                        {
                            Id = 40,
                            ProductID = 14,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8773),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 12500,
                            quantity = 15,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8774),
                            weight = 250
                        },
                        new
                        {
                            Id = 41,
                            ProductID = 14,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8776),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 18000,
                            quantity = 16,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8776),
                            weight = 500
                        },
                        new
                        {
                            Id = 42,
                            ProductID = 14,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8778),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 26000,
                            quantity = 17,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8780),
                            weight = 1000
                        },
                        new
                        {
                            Id = 43,
                            ProductID = 15,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8781),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 16000,
                            quantity = 12,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8782),
                            weight = 250
                        },
                        new
                        {
                            Id = 44,
                            ProductID = 15,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8783),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 32000,
                            quantity = 22,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8783),
                            weight = 500
                        },
                        new
                        {
                            Id = 45,
                            ProductID = 15,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8784),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 60000,
                            quantity = 26,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8785),
                            weight = 1000
                        },
                        new
                        {
                            Id = 46,
                            ProductID = 16,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8786),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 12500,
                            quantity = 4,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8787),
                            weight = 250
                        },
                        new
                        {
                            Id = 47,
                            ProductID = 16,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8788),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 17000,
                            quantity = 22,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8788),
                            weight = 500
                        },
                        new
                        {
                            Id = 48,
                            ProductID = 16,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8789),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 30000,
                            quantity = 9,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8790),
                            weight = 1000
                        },
                        new
                        {
                            Id = 49,
                            ProductID = 17,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8791),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 22000,
                            quantity = 21,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8791),
                            weight = 250
                        },
                        new
                        {
                            Id = 50,
                            ProductID = 17,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8793),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 31000,
                            quantity = 11,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8793),
                            weight = 500
                        },
                        new
                        {
                            Id = 51,
                            ProductID = 17,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8794),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 45500,
                            quantity = 11,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8795),
                            weight = 1000
                        },
                        new
                        {
                            Id = 52,
                            ProductID = 18,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8796),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 15100,
                            quantity = 22,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8796),
                            weight = 250
                        },
                        new
                        {
                            Id = 53,
                            ProductID = 18,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8797),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 18000,
                            quantity = 12,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8798),
                            weight = 500
                        },
                        new
                        {
                            Id = 54,
                            ProductID = 18,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8799),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 21200,
                            quantity = 32,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8800),
                            weight = 1000
                        },
                        new
                        {
                            Id = 55,
                            ProductID = 19,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8801),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 32000,
                            quantity = 21,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8801),
                            weight = 250
                        },
                        new
                        {
                            Id = 56,
                            ProductID = 19,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8802),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 40000,
                            quantity = 11,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8803),
                            weight = 500
                        },
                        new
                        {
                            Id = 57,
                            ProductID = 19,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8804),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 50000,
                            quantity = 15,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8805),
                            weight = 1000
                        },
                        new
                        {
                            Id = 58,
                            ProductID = 20,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8806),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 12000,
                            quantity = 44,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8806),
                            weight = 250
                        },
                        new
                        {
                            Id = 59,
                            ProductID = 20,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8807),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 20000,
                            quantity = 15,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8808),
                            weight = 500
                        },
                        new
                        {
                            Id = 60,
                            ProductID = 20,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8809),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 30000,
                            quantity = 21,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8810),
                            weight = 1000
                        },
                        new
                        {
                            Id = 61,
                            ProductID = 21,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8811),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 8000,
                            quantity = 11,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8811),
                            weight = 250
                        },
                        new
                        {
                            Id = 62,
                            ProductID = 21,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8873),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 16000,
                            quantity = 1,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8874),
                            weight = 500
                        },
                        new
                        {
                            Id = 63,
                            ProductID = 21,
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8875),
                            isAvailable = (byte)1,
                            isDeleted = (byte)0,
                            price = 28000,
                            quantity = 2,
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(8876),
                            weight = 1000
                        });
                });

            modelBuilder.Entity("api.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("altitude_max")
                        .HasColumnType("int");

                    b.Property<int>("altitude_min")
                        .HasColumnType("int");

                    b.Property<string>("bean_type")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("isDeleted")
                        .HasColumnType("tinyint");

                    b.Property<int>("max_price")
                        .HasColumnType("int");

                    b.Property<int>("min_price")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("roast")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            altitude_max = 9000,
                            altitude_min = 7000,
                            bean_type = "Arabic",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 491, DateTimeKind.Local).AddTicks(7101),
                            desc = "Ethiopian Limu is from the western escarpments of the Ethiopian highlands. Our single origin is a fully washed, high quality coffee with rich, round flavour and a pronounced sweetness on the palate.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 28000,
                            min_price = 8000,
                            name = "ETHIOPIAN LIMU",
                            region = "Ethiopia",
                            roast = "light",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 492, DateTimeKind.Local).AddTicks(8290)
                        },
                        new
                        {
                            Id = 2,
                            altitude_max = 2500,
                            altitude_min = 2000,
                            bean_type = "Hierloom",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(637),
                            desc = "Guji is one of those regions of Ethiopia that have garnered much more attention in recent years, competing with the classically popular areas like Yirgacheffe & Limu.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 31000,
                            min_price = 9000,
                            name = "Truth. - Ethiopia Guji",
                            region = "Ethiopia",
                            roast = "Medium",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(649)
                        },
                        new
                        {
                            Id = 3,
                            altitude_max = 1800,
                            altitude_min = 1600,
                            bean_type = "Arabic",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(657),
                            desc = "Truth seems to have had a bit of a love affair with Burundian coffee in the last few years, one from which we have all benefited. They've had a streak of delicious examples of the up and coming coffee producing country's very best exports that we have thoroughly enjoyed.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 32000,
                            min_price = 10000,
                            name = "Truth. - Burundi",
                            region = "Burundi",
                            roast = "light",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(658)
                        },
                        new
                        {
                            Id = 4,
                            altitude_max = 10000,
                            altitude_min = 9500,
                            bean_type = "Blend",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(660),
                            desc = "Bean There's Blend 44 combines their very popular Ethiopia Sidamo, and one of our favourites, their Burundi Musema & Nyarurama. The marriage of these two wonderful coffees yields everything you might want in a bold yet balanced coffee, suitable for manual brewing or espresso.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 25000,
                            min_price = 6000,
                            name = "Bean There - Blend 44",
                            region = "Ethiopia",
                            roast = "Light",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(660)
                        },
                        new
                        {
                            Id = 5,
                            altitude_max = 9000,
                            altitude_min = 7000,
                            bean_type = "Arabic",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(662),
                            desc = "Villa Rosario is a colony in the Caranavi area of Yungus. The colony is located between 1550 and 1650 masl and is surrounded by jungle and small coffee farms.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 16000,
                            min_price = 8000,
                            name = "Legado - Bolivia Villa Rosario Organic",
                            region = "Bolivia",
                            roast = "Dark",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(663)
                        },
                        new
                        {
                            Id = 6,
                            altitude_max = 1700,
                            altitude_min = 1675,
                            bean_type = "Primarily Caturra & Catuai",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(664),
                            desc = "Origin Coffee Roasting's decafs are surprisingly delicious. They select top quality single origin beans that are decaffeinated using a chemical-free process, to ensure maximum flavour retention and no unpleasant artificial qualities.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 35000,
                            min_price = 15000,
                            name = "Origin Coffee Roasting - Guatemala Santa Sofia",
                            region = "Guatamala",
                            roast = "light",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(665)
                        },
                        new
                        {
                            Id = 7,
                            altitude_max = 1600,
                            altitude_min = 1220,
                            bean_type = "Heirloom",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(668),
                            desc = "This Costa Rican single origin coffee from The Portland Project has everything that you might look for from that part of the coffee growing world. Its acidity is very discrete and body is full and satisfying.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 29000,
                            min_price = 10000,
                            name = "Portland Project - Costa Rica Trojas",
                            region = "Costa Rica",
                            roast = "Dark",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(668)
                        },
                        new
                        {
                            Id = 8,
                            altitude_max = 1200,
                            altitude_min = 1100,
                            bean_type = "Finca Idealista",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(670),
                            desc = "This is a spectacularly and deliciously unusual coffee. Its flavours are quite different from anything we've tasted before, and this may be in part due to the experimental processing method employed.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 17000,
                            min_price = 10000,
                            name = "Quaffee - Nicaragua Finca Idealista Anaerobic Nanolot",
                            region = "Nicaragua",
                            roast = "Medium",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(670)
                        },
                        new
                        {
                            Id = 9,
                            altitude_max = 1600,
                            altitude_min = 1420,
                            bean_type = "Catui",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(673),
                            desc = "While Central American coffee is generally well-respected, Honduras is definitely one of the lesser known producers in the region, at least here in South Africa. Equally many of the best Central American coffees are quite reserved in their flavour profiles.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 32000,
                            min_price = 18000,
                            name = "Rosetta Roastery - Honduras San Franscisco Natural",
                            region = "Honduras",
                            roast = "Dark",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(673)
                        },
                        new
                        {
                            Id = 10,
                            altitude_max = 9000,
                            altitude_min = 7000,
                            bean_type = "BVurundi",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(675),
                            desc = "Bourbon type varietal.Cup profiles can be dynamic and bright, with red fruits, berry or citrus.Medium body and rounded mouth feel with a lingering finish.It’s no secret that Burundi has the potential to produce great coffee.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 36000,
                            min_price = 10000,
                            name = "BURUNDI KIBIRA",
                            region = "India",
                            roast = "light",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(675)
                        },
                        new
                        {
                            Id = 11,
                            altitude_max = 1350,
                            altitude_min = 1000,
                            bean_type = "Cauvery",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(677),
                            desc = "The coffee comes from the Allana estate in the former state of Mysore in India, now part of Karnataka. While the geographic area no longer bears the name, the coffees from that area are still referred to as Indian Mysore.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 28000,
                            min_price = 8000,
                            name = "Truth. - India Single Origin",
                            region = "India",
                            roast = "Medium",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(678)
                        },
                        new
                        {
                            Id = 12,
                            altitude_max = 9000,
                            altitude_min = 7000,
                            bean_type = "Arabic",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(679),
                            desc = "Ethiopian Limu is from the western escarpments of the Ethiopian highlands. Our single origin is a fully washed, high quality coffee with rich, round flavour and a pronounced sweetness on the palate.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 28000,
                            min_price = 8000,
                            name = "ETHIOPIAN LIMU",
                            region = "Ethiopia",
                            roast = "light",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(680)
                        },
                        new
                        {
                            Id = 13,
                            altitude_max = 2000,
                            altitude_min = 1700,
                            bean_type = "Red Bourbon",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(682),
                            desc = "Rwanda Musasa is a returning favourite from Origin Coffee Roasting. Highly celebrated, the Musasa Dukunde Kawa Cooperative is known all over the world for its top quality Red Bourbon beans.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 28000,
                            min_price = 8000,
                            name = "Origin Coffee Roasting - Rwanda Musasa Ruli",
                            region = "Ruli",
                            roast = "light",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(682)
                        },
                        new
                        {
                            Id = 14,
                            altitude_max = 1200,
                            altitude_min = 1100,
                            bean_type = "Blend",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(684),
                            desc = "This blend was concocted early one morning when there just wasn't enough of one of the components, and a certain CCTeam member thought, 'what the heck ?'  And so, a blend was born, and it tasted like fruit salad in a cup. It kind of makes sense in the end if you think about it.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 26000,
                            min_price = 12500,
                            name = "Fruit Salad Cape Coffee Blend",
                            region = "South Afica",
                            roast = "Medium",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(685)
                        },
                        new
                        {
                            Id = 15,
                            altitude_max = 1600,
                            altitude_min = 1550,
                            bean_type = "Catuai",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(686),
                            desc = "While Central American coffee is generally well-respected, Honduras is definitely one of the lesser known producers in the region, at least here in South Africa. Equally many of the best Central American coffees are quite reserved in their flavour profiles.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 60000,
                            min_price = 16000,
                            name = "Rosetta Roastery - Honduras San Franscisco Natural",
                            region = "Marcala",
                            roast = "Dark",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(687)
                        },
                        new
                        {
                            Id = 16,
                            altitude_max = 9000,
                            altitude_min = 7000,
                            bean_type = "Blend",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(688),
                            desc = "häzz coffee is a rich and subtle, truly modern blend of South American and African origin, suitable for any palate.  It offers an exceptionally wide range of aromas, accompanied by a bold but round and smooth body.In 2012, it won a Gold Medal at the annual International Coffee Tasting in Italy.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 30000,
                            min_price = 12500,
                            name = "hazz blend - coffee for heroes",
                            region = "South America and Africa",
                            roast = "light",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(689)
                        },
                        new
                        {
                            Id = 17,
                            altitude_max = 9000,
                            altitude_min = 7000,
                            bean_type = "Blend",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(690),
                            desc = "Tribe Coffee's Espresso Blend has quickly earned them a reputation in and around Cape Town. Full-bodied and well-developed, it makes great milk & espresso-based drinks which is why you'll find it in many restaurants and cafés in the Mother City!",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 45500,
                            min_price = 22000,
                            name = "Tribe Coffee - Espresso Blend",
                            region = "SouthAfrica",
                            roast = "Dark",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(691)
                        },
                        new
                        {
                            Id = 18,
                            altitude_max = 9000,
                            altitude_min = 7000,
                            bean_type = "Harrar",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(693),
                            desc = "Heavy-bodied, spicy and fragrant, Ethiopian Harrar coffee is a wild and exotic dry processed (natural) Arabica coffee that is grown on small farms in the Oromia region (formerly Harrar) in southern Ethiopia at elevations between 1,400 meters and 2,000 meters.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 21200,
                            min_price = 15100,
                            name = "ETHIOPIAN HARRAR",
                            region = "Ethiopia",
                            roast = "Medium",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(693)
                        },
                        new
                        {
                            Id = 19,
                            altitude_max = 9000,
                            altitude_min = 7000,
                            bean_type = "Arabica",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(695),
                            desc = "A full bodied, sweet with fruity after taste. We roast this coffee medium-dark to maintain the complex flavours, a coffee that will place a smile on any connoisseurs face.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 50000,
                            min_price = 32000,
                            name = "BRU Etheopia",
                            region = "Ethiopia",
                            roast = "Medium",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(696)
                        },
                        new
                        {
                            Id = 20,
                            altitude_max = 10000,
                            altitude_min = 9000,
                            bean_type = "Catuai",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(697),
                            desc = "A filter grind perfect for plungers, pour overs and more. We've selected 5 varieties of coffee beans for our premium Alpha coffee blend. Rich fruited aromas with a hint of spice. Stoned fruit, nuts and apricot. Balanced citrus and acidity",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 30000,
                            min_price = 12000,
                            name = "Coffee Lab Alpha",
                            region = "South Africa",
                            roast = "Dark",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(699)
                        },
                        new
                        {
                            Id = 21,
                            altitude_max = 5000,
                            altitude_min = 3500,
                            bean_type = "Arabic",
                            created_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(701),
                            desc = "Turkish Coffee ground to the finest Powder with a touch of elachi spice for that exotic flavour.",
                            image_url = "404.jpg",
                            isDeleted = (byte)0,
                            max_price = 28000,
                            min_price = 8000,
                            name = "Titanium Coffee Turkish",
                            region = "Turkish",
                            roast = "Dark",
                            updated_at = new DateTime(2019, 10, 16, 0, 37, 29, 493, DateTimeKind.Local).AddTicks(701)
                        });
                });

            modelBuilder.Entity("api.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("contact_number")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("isActive")
                        .HasColumnType("tinyint");

                    b.Property<byte>("isAdmin")
                        .HasColumnType("tinyint");

                    b.Property<byte>("isDelted")
                        .HasColumnType("tinyint");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("api.Models.InvoiceItems", b =>
                {
                    b.HasOne("api.Models.Invoices", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("api.Models.Invoices", b =>
                {
                    b.HasOne("api.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("api.Models.ProductOptions", b =>
                {
                    b.HasOne("api.Models.Products", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
